### ISSUE TITLE
Use xip.io instead of modifying /etc/hosts

### ISSUE THREAD

**Issue by flolivaud** [thecodingmachine/kickoff-docker-php#12]
If you use http://xip.io/, no need to modify /etc/hosts (or system32 in windows ...).

**Comment by gulien** [comment]
Thank you for the tip! Do you have any hints to help us using it?

**Comment by flolivaud** [comment]
Hey,

for example, instead of using : 
-  `traefik.my-awesome-project.local` use the domain `traefik.my-project.127.0.0.1.xip.io` will do the same, but no host modification needed.

So you just need to modify the domain in your config file i guess.

**Comment by gulien** [comment]
Great, I'll take a look and try it!
