### ISSUE TITLE
Is it ok to use martin/docker-cleanup-volumes ?

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/kickoff-docker-php#3]
The _down script uses martin/docker-cleanup-volumes

But according to the documentation (https://hub.docker.com/r/martin/docker-cleanup-volumes/), this is only tested up to Docker 1.10.
Most people now a day use Docker 1.12, that comes with a native way to clean volumes (see https://hub.docker.com/r/martin/docker-cleanup-volumes)

Should we not rely on the native docker feature instead?

**Comment by gulien** [comment]
You're right. I've implemented it as shown in https://github.com/thecodingmachine/kickoff-docker-php/blob/master/bin/_down#L14

Seems good to you?

**Comment by moufmouf** [comment]
Yeah! :+1:
